version: '3'
services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
